"""add tailored score

Revision ID: 259542b813f4
Revises: 60fac35f7ebe
Create Date: 2026-08-27 12:58:42.636882

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '259542b813f4'
down_revision: Union[str, None] = '60fac35f7ebe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resume_versions', sa.Column('tailored_score', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('resume_versions', 'tailored_score')
    # ### end Alembic commands ###