"""add resume versions

Revision ID: 60fac35f7ebe
Revises: 9d8c6f39dc19
Create Date: 2026-08-22 18:04:03.468332

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '60fac35f7ebe'
down_revision: Union[str, None] = '9d8c6f39dc19'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('resume_versions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('resume_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('job_description', sa.Text(), nullable=False),
    sa.Column('analysis_score', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['resume_id'], ['resumes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_resume_versions_id'), 'resume_versions', ['id'], unique=False)
    op.create_index(op.f('ix_resume_versions_resume_id'), 'resume_versions', ['resume_id'], unique=False)
    op.create_index(op.f('ix_resume_versions_user_id'), 'resume_versions', ['user_id'], unique=False)
    op.create_table('version_source_certifications',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('issuer', sa.String(length=200), nullable=True),
    sa.Column('date_obtained', sa.String(length=7), nullable=True),
    sa.Column('url', sa.String(length=2048), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('version_id', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['version_id'], ['resume_versions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_version_source_certifications_id'), 'version_source_certifications', ['id'], unique=False)
    op.create_index(op.f('ix_version_source_certifications_version_id'), 'version_source_certifications', ['version_id'], unique=False)
    op.create_table('version_source_education',
    sa.Column('institution', sa.String(length=200), nullable=False),
    sa.Column('degree', sa.String(length=200), nullable=True),
    sa.Column('field_of_study', sa.String(length=200), nullable=True),
    sa.Column('start_date', sa.String(length=7), nullable=True),
    sa.Column('end_date', sa.String(length=7), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('version_id', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['version_id'], ['resume_versions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_version_source_education_id'), 'version_source_education', ['id'], unique=False)
    op.create_index(op.f('ix_version_source_education_version_id'), 'version_source_education', ['version_id'], unique=False)
    op.create_table('version_source_experience',
    sa.Column('company', sa.String(length=200), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('location', sa.String(length=100), nullable=True),
    sa.Column('start_date', sa.String(length=7), nullable=True),
    sa.Column('end_date', sa.String(length=7), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('version_id', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['version_id'], ['resume_versions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_version_source_experience_id'), 'version_source_experience', ['id'], unique=False)
    op.create_index(op.f('ix_version_source_experience_version_id'), 'version_source_experience', ['version_id'], unique=False)
    op.create_table('version_source_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('version_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=True),
    sa.Column('full_name', sa.String(length=100), nullable=True),
    sa.Column('email', sa.String(length=254), nullable=True),
    sa.Column('phone', sa.String(length=30), nullable=True),
    sa.Column('location', sa.String(length=100), nullable=True),
    sa.Column('website', sa.String(length=2048), nullable=True),
    sa.Column('linkedin', sa.String(length=2048), nullable=True),
    sa.Column('github', sa.String(length=2048), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['version_id'], ['resume_versions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_version_source_profiles_id'), 'version_source_profiles', ['id'], unique=False)
    op.create_index(op.f('ix_version_source_profiles_version_id'), 'version_source_profiles', ['version_id'], unique=False)
    op.create_table('version_source_projects',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('url', sa.String(length=2048), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('version_id', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['version_id'], ['resume_versions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_version_source_projects_id'), 'version_source_projects', ['id'], unique=False)
    op.create_index(op.f('ix_version_source_projects_version_id'), 'version_source_projects', ['version_id'], unique=False)
    op.create_table('version_source_skills',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('version_id', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['version_id'], ['resume_versions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_version_source_skills_id'), 'version_source_skills', ['id'], unique=False)
    op.create_index(op.f('ix_version_source_skills_version_id'), 'version_source_skills', ['version_id'], unique=False)
    op.create_table('version_tailored_certifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('version_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('issuer', sa.String(length=200), nullable=True),
    sa.Column('date_obtained', sa.String(length=7), nullable=True),
    sa.Column('url', sa.String(length=2048), nullable=True),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['version_id'], ['resume_versions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_version_tailored_certifications_id'), 'version_tailored_certifications', ['id'], unique=False)
    op.create_index(op.f('ix_version_tailored_certifications_version_id'), 'version_tailored_certifications', ['version_id'], unique=False)
    op.create_table('version_tailored_education',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('version_id', sa.Integer(), nullable=False),
    sa.Column('institution', sa.String(length=200), nullable=False),
    sa.Column('degree', sa.String(length=200), nullable=True),
    sa.Column('field_of_study', sa.String(length=200), nullable=True),
    sa.Column('start_date', sa.String(length=7), nullable=True),
    sa.Column('end_date', sa.String(length=7), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['version_id'], ['resume_versions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_version_tailored_education_id'), 'version_tailored_education', ['id'], unique=False)
    op.create_index(op.f('ix_version_tailored_education_version_id'), 'version_tailored_education', ['version_id'], unique=False)
    op.create_table('version_tailored_experience',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('version_id', sa.Integer(), nullable=False),
    sa.Column('company', sa.String(length=200), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('location', sa.String(length=100), nullable=True),
    sa.Column('start_date', sa.String(length=7), nullable=True),
    sa.Column('end_date', sa.String(length=7), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['version_id'], ['resume_versions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_version_tailored_experience_id'), 'version_tailored_experience', ['id'], unique=False)
    op.create_index(op.f('ix_version_tailored_experience_version_id'), 'version_tailored_experience', ['version_id'], unique=False)
    op.create_table('version_tailored_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('version_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=True),
    sa.Column('full_name', sa.String(length=100), nullable=True),
    sa.Column('email', sa.String(length=254), nullable=True),
    sa.Column('phone', sa.String(length=30), nullable=True),
    sa.Column('location', sa.String(length=100), nullable=True),
    sa.Column('website', sa.String(length=2048), nullable=True),
    sa.Column('linkedin', sa.String(length=2048), nullable=True),
    sa.Column('github', sa.String(length=2048), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['version_id'], ['resume_versions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_version_tailored_profiles_id'), 'version_tailored_profiles', ['id'], unique=False)
    op.create_index(op.f('ix_version_tailored_profiles_version_id'), 'version_tailored_profiles', ['version_id'], unique=False)
    op.create_table('version_tailored_projects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('version_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('url', sa.String(length=2048), nullable=True),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['version_id'], ['resume_versions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_version_tailored_projects_id'), 'version_tailored_projects', ['id'], unique=False)
    op.create_index(op.f('ix_version_tailored_projects_version_id'), 'version_tailored_projects', ['version_id'], unique=False)
    op.create_table('version_tailored_skills',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('version_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['version_id'], ['resume_versions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_version_tailored_skills_id'), 'version_tailored_skills', ['id'], unique=False)
    op.create_index(op.f('ix_version_tailored_skills_version_id'), 'version_tailored_skills', ['version_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_version_tailored_skills_version_id'), table_name='version_tailored_skills')
    op.drop_index(op.f('ix_version_tailored_skills_id'), table_name='version_tailored_skills')
    op.drop_table('version_tailored_skills')
    op.drop_index(op.f('ix_version_tailored_projects_version_id'), table_name='version_tailored_projects')
    op.drop_index(op.f('ix_version_tailored_projects_id'), table_name='version_tailored_projects')
    op.drop_table('version_tailored_projects')
    op.drop_index(op.f('ix_version_tailored_profiles_version_id'), table_name='version_tailored_profiles')
    op.drop_index(op.f('ix_version_tailored_profiles_id'), table_name='version_tailored_profiles')
    op.drop_table('version_tailored_profiles')
    op.drop_index(op.f('ix_version_tailored_experience_version_id'), table_name='version_tailored_experience')
    op.drop_index(op.f('ix_version_tailored_experience_id'), table_name='version_tailored_experience')
    op.drop_table('version_tailored_experience')
    op.drop_index(op.f('ix_version_tailored_education_version_id'), table_name='version_tailored_education')
    op.drop_index(op.f('ix_version_tailored_education_id'), table_name='version_tailored_education')
    op.drop_table('version_tailored_education')
    op.drop_index(op.f('ix_version_tailored_certifications_version_id'), table_name='version_tailored_certifications')
    op.drop_index(op.f('ix_version_tailored_certifications_id'), table_name='version_tailored_certifications')
    op.drop_table('version_tailored_certifications')
    op.drop_index(op.f('ix_version_source_skills_version_id'), table_name='version_source_skills')
    op.drop_index(op.f('ix_version_source_skills_id'), table_name='version_source_skills')
    op.drop_table('version_source_skills')
    op.drop_index(op.f('ix_version_source_projects_version_id'), table_name='version_source_projects')
    op.drop_index(op.f('ix_version_source_projects_id'), table_name='version_source_projects')
    op.drop_table('version_source_projects')
    op.drop_index(op.f('ix_version_source_profiles_version_id'), table_name='version_source_profiles')
    op.drop_index(op.f('ix_version_source_profiles_id'), table_name='version_source_profiles')
    op.drop_table('version_source_profiles')
    op.drop_index(op.f('ix_version_source_experience_version_id'), table_name='version_source_experience')
    op.drop_index(op.f('ix_version_source_experience_id'), table_name='version_source_experience')
    op.drop_table('version_source_experience')
    op.drop_index(op.f('ix_version_source_education_version_id'), table_name='version_source_education')
    op.drop_index(op.f('ix_version_source_education_id'), table_name='version_source_education')
    op.drop_table('version_source_education')
    op.drop_index(op.f('ix_version_source_certifications_version_id'), table_name='version_source_certifications')
    op.drop_index(op.f('ix_version_source_certifications_id'), table_name='version_source_certifications')
    op.drop_table('version_source_certifications')
    op.drop_index(op.f('ix_resume_versions_user_id'), table_name='resume_versions')
    op.drop_index(op.f('ix_resume_versions_resume_id'), table_name='resume_versions')
    op.drop_index(op.f('ix_resume_versions_id'), table_name='resume_versions')
    op.drop_table('resume_versions')
    # ### end Alembic commands ###